spring.application.name=motusbot

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/motusDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

bot.name=MotusBot
bot.token=8019991456:AAFN-KFUbk5Tfpsk4gKoWwDd2PRH2SngiOs

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migration/changelog/master.xml
spring.liquibase.contexts=dev,prod

server.port=8080
logging.level.root=INFO
